import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tshep
 */
public class MovieSearcher extends javax.swing.JFrame {
    
    ServerConnection conn = new ServerConnection();

    /**
     * Creates new form MovieSearcher
     */
    public MovieSearcher() {
        initComponents();
        findUsers();
    }
    
    public static Connection getConnection() {
   
        Connection con = null;
       try {
           con = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-Q19MT48:1433;databaseName=Movies;user=tshepang;password=Tshepang@1234567;");
        } catch (Exception ex) {
           System.out.println(ex.getMessage());
        }
       return con;
    }
    
    public ArrayList<MovieData> ListUsers(String ValToSearch)
    {
        ArrayList<MovieData> movieList = new ArrayList<MovieData>();
        
        Statement ps3;
        ResultSet rs;
        
        try {
           Connection con = getConnection();
           ps3 = con.createStatement();
           String searchQuery = "SELECT * FROM Movie WHERE CONCAT(movieName,genreId) LIKE '%"+ValToSearch+"%'";
           rs = ps3.executeQuery(searchQuery);
           
           MovieData user;
           
          while (rs.next()) {
                        
              user = new MovieData(
              
                                rs.getInt("genreId"),
                                rs.getString("movieName")
                 
              
              ); 
             movieList.add(user);         
              
          
              
                      
       } 
           
          
            
        } catch (Exception ex) {
           System.out.println(ex.getMessage());
        }
        
        return movieList;
    }
    
    
    public void findUsers()
    {
        ArrayList<MovieData> users = ListUsers(jTextField_Searcher.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"moveName","genreId"});
        Object [] row = new Object[2];
        
        for (int i = 0; i<users.size();i++)
        {
            row[0] = users.get(i).getMName();
            row[1] = users.get(i).getgenreId();
            model.addRow(row);
        }
        jTable_Movies.setModel(model);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Closebutton = new javax.swing.JLabel();
        jLabel_min = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_MName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField_MGenre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_GCatagory = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Searcher = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Movies = new javax.swing.JTable();
        jLabel_RegLink = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton_StartUp = new javax.swing.JButton();
        jButton_Shutdown = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 230, 64));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Movie Searcher");

        jLabel_Closebutton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel_Closebutton.setText("x");
        jLabel_Closebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ClosebuttonMouseClicked(evt);
            }
        });

        jLabel_min.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel_min.setText("-");
        jLabel_min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_min)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Closebutton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(jLabel_Closebutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_min, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(31, 58, 147));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Movie Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Movie Genre:");

        jTextField_MName.setBackground(new java.awt.Color(30, 139, 195));
        jTextField_MName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_MName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MNameActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(30, 139, 195));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField_MGenre.setBackground(new java.awt.Color(30, 139, 195));
        jTextField_MGenre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_MGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MGenreActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Genre Catagory:");

        jTextField_GCatagory.setBackground(new java.awt.Color(30, 139, 195));
        jTextField_GCatagory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_GCatagory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_GCatagoryActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Search:");

        jTextField_Searcher.setBackground(new java.awt.Color(30, 139, 195));
        jTextField_Searcher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Searcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SearcherActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(30, 139, 195));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable_Movies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Movies);

        jLabel_RegLink.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_RegLink.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_RegLink.setText("Click for the Genre Catagories");
        jLabel_RegLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_RegLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RegLinkMouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(30, 139, 195));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton_StartUp.setBackground(new java.awt.Color(30, 139, 195));
        jButton_StartUp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_StartUp.setText("Start Up");
        jButton_StartUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_StartUpActionPerformed(evt);
            }
        });

        jButton_Shutdown.setBackground(new java.awt.Color(30, 139, 195));
        jButton_Shutdown.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Shutdown.setText("Shutdown");
        jButton_Shutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ShutdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_GCatagory, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_MGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_MName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(35, 35, 35))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Searcher, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton_StartUp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Shutdown))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel_RegLink)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_MName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_MGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_GCatagory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_Searcher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jLabel_RegLink)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_StartUp)
                    .addComponent(jButton_Shutdown))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_ClosebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ClosebuttonMouseClicked

        System.exit(0);

    }//GEN-LAST:event_jLabel_ClosebuttonMouseClicked

    private void jLabel_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minMouseClicked

        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jLabel_minMouseClicked

    private void jTextField_MNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        
        String MG = jTextField_MGenre.getText();
        
        
        PreparedStatement ps;
        String query = "INSERT INTO Genre (genreName)"
       + " VALUES (?)";
        
        try{
        ps = ServerConnection.getConnection().prepareStatement(query);
        
        ps.setString(1, MG);
        
        
        } catch(SQLException ex){
            Logger.getLogger(MovieSearcher.class.getName()).log(Level.SEVERE,null,ex);
        }
        String MN = jTextField_MName.getText();
        String GC = jTextField_GCatagory.getText();
        
        PreparedStatement ps2;
        String query2 = "INSERT INTO Movie (movieName,genreId)"
       + " VALUES (?,?)";
        
        try{
        ps2 = ServerConnection.getConnection().prepareStatement(query2);
        
        ps2.setString(1, MN);
        ps2.setInt(2,Integer.parseInt(GC));
        
        if(ps2.executeUpdate()>0)
        {
            JOptionPane.showMessageDialog(null,"New Movie Added");
        }
        
        } catch(SQLException ex){
            Logger.getLogger(MovieSearcher.class.getName()).log(Level.SEVERE,null,ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField_MGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MGenreActionPerformed

    private void jTextField_GCatagoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_GCatagoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GCatagoryActionPerformed

    private void jTextField_SearcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SearcherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SearcherActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        findUsers();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel_RegLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegLinkMouseClicked

        GenreKeys GK = new GenreKeys();
        GK.setVisible(true);
        GK.pack();
        GK.setLocationRelativeTo(null);
        GK.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_jLabel_RegLinkMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                                                

        String MN1 = jTextField_MName.getText();

        
        PreparedStatement ps3;
        String query3 = "DELETE FROM Movie WHERE movieName = '?'";
        
        try{
        ps3 = ServerConnection.getConnection().prepareStatement(query3);
        
        ps3.setString(1, MN1);

        
        if(ps3.executeUpdate()>0)
        {
            JOptionPane.showMessageDialog(null,"Movie Deleted");
        }
        
        } catch(SQLException ex){
            Logger.getLogger(MovieSearcher.class.getName()).log(Level.SEVERE,null,ex);
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton_ShutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ShutdownActionPerformed
        if (conn != null)
        {
             conn.close();
             
        }
        System.exit(0);
    }//GEN-LAST:event_jButton_ShutdownActionPerformed

    private void jButton_StartUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_StartUpActionPerformed
        
        conn.getConnection();
        ServerClientConnection ser = new ServerClientConnection();
        ser.serverToClient();
        
    }//GEN-LAST:event_jButton_StartUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieSearcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieSearcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieSearcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieSearcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieSearcher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_Shutdown;
    private javax.swing.JButton jButton_StartUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Closebutton;
    private javax.swing.JLabel jLabel_RegLink;
    private javax.swing.JLabel jLabel_min;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Movies;
    private javax.swing.JTextField jTextField_GCatagory;
    private javax.swing.JTextField jTextField_MGenre;
    private javax.swing.JTextField jTextField_MName;
    private javax.swing.JTextField jTextField_Searcher;
    // End of variables declaration//GEN-END:variables
}
